[project]
name = "news-aggregator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-textanalytics==5.3.0",
    "dotenv>=0.9.9",
    "newsapi-python==0.2.7",
    "requests>=2.32.4",
]
